<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>promisses 2</title>
</head>

<body>
    <script>
        /**
         * 
         * contexto promisses
         **/
        let resposta = {}
        let promise = new Promise((resolve, reject) => {


                setTimeout(() => {
                    let resposta = {}
                    if (false) {
                        resposta = {
                            codigo: 1050,
                            menssagem: "falha de autrizacao"
                        }
                        reject(resposta)
                    }
                    resposta = {
                        0: {
                            id: 1,
                            nome: "joao"
                        },
                        2: {
                            id: 2,
                            nome: "joao"
                        },
                        3: {
                            id: 3,
                            nome: "joao"
                        }
                    }
                    resolve(resposta)
                }, 4000)

            }).then(dados => {
                console.log("Operacao sequencial ", dados)
                return 'Parametro 1 para o then 2'

            }).then(param => {
                console.log("2 Operacao sequencial ", param)
                return 'Parametro 2 para o then'
            }).catch(err => {
                console.log("operacao catch ", err)
                return 'Parametro recebido no catch'
            })
            .then(dados => {
                console.log("Operacao sequencial6 ", dados)
            })
            .then(dados => {
                let promises = new Promise((resolve, reject) => {
                    setTimeout(() => {
                        let resposta = {}
                        if (false) {
                            resposta = {
                                codigo: 788,
                                menssagem: "Erro ao recuperar posts"
                            }
                            reject(resposta)
                        }
                        resposta = {
                            0: {
                                id: 1,
                                nome: "joao",
                                posts: [{
                                    id: 1,
                                    post: 'Post'
                                }, {
                                    id: 2,
                                    post: 'Post2'
                                }]
                            },
                            2: {
                                id: 2,
                                nome: "joao",
                                posts: [{
                                    id: 1,
                                    post: 'Post'
                                }, {
                                    id: 2,
                                    post: 'Post2'
                                }]
                            },
                            3: {
                                id: 3,
                                nome: "joao",
                                posts: [{
                                    id: 1,
                                    post: 'Post'
                                }, {
                                    id: 2,
                                    post: 'Post2'
                                }]
                            }
                        }
                        resolve(resposta)
                    }, 4000)
                }).then(dados => {
                    console.log(dados)
                }).catch(err => {
                    console.log(err)
                })
            })
    </script>


</body>

</html>